### ISSUE TITLE
Stuck at random step while trying to install Squirrel through Carthage

### ISSUE THREAD

**Issue by psequel** [Squirrel/Squirrel.Mac#146]
There is only one line in my Cartfile, `github "Squirrel/Squirrel.Mac" == 0.1.6`. Tried `cart update` a few times and it never succeed -- stuck at a different step each time. Removing `carthage` and `org.carthage.CarthageKit` directories in `~/Library/Caches` doesn't help.

**Comment by keithduncan** [comment]
This seems like a Carthage issue, could you open an issue in [Carthage](https://github.com/Carthage/Carthage/issues) including details of which version of carthage you have installed.
