### ISSUE TITLE
Update fails (OSStatus error -60005)

### ISSUE THREAD

**Issue by bostondv** [Squirrel/Squirrel.Mac#148]
I'm working on an update to our Electron app that updates from Atom Shell v0.20.8 to Electron v0.27.3. Running the auto updater in app results in this error during the download:

`The operation couldn’t be completed. (OSStatus error -60005.)`

I've checked everything I could think of. Code signing on old and new versions of the .app is valid, the update is successfully found on the server and have validated that the zip file is error free.

Any suggestions how to resolve?

Originally posted in Electron https://github.com/atom/electron/issues/2005

**Comment by mdiep** [comment]
The error code is [errAuthorizationDenied](https://developer.apple.com/library/mac/documentation/Security/Reference/authorization_ref/index.html#//apple_ref/c/econst/errAuthorizationDenied).

**Comment by bostondv** [comment]
Thanks, is there something I can do to make it allow authorization?

**Comment by joshaber** [comment]
Stale.

**Comment by atdrago** [comment]
@bostondv I know this is old, but did you ever get an answer? I'm having the same issue with my Electron app.

**Comment by fancyydk** [comment]
If you don't use a dmg, is there a different way to install the app? I'm running into this -60005 error and -60006 error as well which stand for errAuthorziationDenied and errAuthorizationCanceled, respectively. Any answers?

**Comment by marcpom** [comment]
In case anyone else runs into this, it seems to be a sandbox issue with authorization.

Since we are doing a developer ID build (not for MAS), what worked for us is simply disabling sandboxing and entitlements, by removing the "entitlements" property from the build config. It was our mistake keeping it enabled from the MAS build.
