### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by jenslind** [Squirrel/Squirrel.Mac#155]
Looks like there is support for using GitHub releases as your host in Squirrel for windows.
https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/api.md#github-updatemanager

Are there any plans on adding this feature to Mac?

**Comment by keithduncan** [comment]
We are keen to add support for updating from static resources as discussed in https://github.com/Squirrel/Squirrel.Mac/issues/64 but decided against it for our initial release.

> Are there any plans on adding this feature to Mac?

I can’t say any of us plan to work on this in the near term :grimacing: 

I’m going to close this in favour of the static update resources issue I linked to, thank you for filing your question though :bow:

**Comment by jenslind** [comment]
Alright, thanks!
