### ISSUE TITLE
Can't extract the update zip file in .ShipIt

### ISSUE THREAD

**Issue by tom2zip** [Squirrel/Squirrel.Mac#158]
I have the auto update set up for my Electron app. The actual update fails with the following error:
Could not locate update bundle for com.{appname} within file:///Users/{me}/Library/Application%20Support/com.{appname}.ShipIt/update.nQcEUZ3/: (null)

I can see the zip file from my update server being downloaded but the whole update folder (update.nQcEUZ3 in that particular case) gets deleted right after. No Shipit_stderr or stdout created either.

Any help will be appreciated, thanks.

**Comment by bitomule** [comment]
I also have this issue, any idea on how to fix it?

**Comment by bitomule** [comment]
Can anyone help me with this please?

**Comment by joshaber** [comment]
Off the top of my head I don't know what would be causing it. GitHub Desktop and Atom both use it and, AFAIK, don't have this problem. So we'd need more information about *how* you're using it to begin to debug.

**Comment by bitomule** [comment]
Thanks @joshaber. I'll try to share all I know. I'm using:

- electron 0.35.2
- electron-packager 5.1.1
- electron-gh-releases 2.0.2
- electron-release 2.2.0

I build the app using:
```
electron-packager ./ myapp --out=dist/osx --platform=darwin --arch=all --version=0.35.2 --app-version 1.0.3 --app-bundle-id=myapp --helper-bundle-id=myapp --overwrite=true --asar=true --icon=assets/osx/myapp.icns --prune=true --ignore=dist --sign="mycert"
```

Once I have the app I upload it to github using electron-release:

```
electron-release --app="dist/osx/myapp.dmg" --output="dist/osx/mmmelon.zip"  --token=myGithubToken
```

If you know of any test or change I can do I'll do anything trying to help with the error.

**Comment by joshaber** [comment]
I'm not sure how electron-gh-releases works but that seems like a likely subject.

**Comment by bitomule** [comment]
electron-gh-releases seems to be working file. It just gives electron auto updater the zip url. Squirrel downloads the zip but then it's removed and and error is thrown.

In this line it sets the feedUrl. Is that fine? Not sure where squirrel starts it's work.
https://github.com/jenslind/electron-gh-releases/blob/master/src/GhReleases.js#L129

**Comment by joshaber** [comment]
My guess is that the code signature check failed.

**Comment by bitomule** [comment]
@joshaber so maybe the issue is with electron-packager? Does Atom or Github desktop use other osx packager? Any help on how to debug the issue would be great :)

**Comment by joshaber** [comment]
>so maybe the issue is with electron-packager?

Maybe, or with the cert?

>Does Atom or Github desktop use other osx packager?

They both use different methods for packaging the apps.

>Any help on how to debug the issue would be great :)

Check out the `codesign` utility. E.g., `codesign --verify -vvvv /path/to/your/app`.

**Comment by bitomule** [comment]
Thanks @joshaber just downloaded the zip from the github repo (the one downloaded to update) and runned codesign verify on it, here's the output:

```
--prepared:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/myapp Helper.app
--validated:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/myapp Helper.app
--prepared:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--validated:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/Mantle.framework/Versions/Current/.
--prepared:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/myapp Helper NP.app
--validated:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/myapp Helper NP.app
--prepared:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/myapp Helper EH.app
--validated:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/myapp Helper EH.app
--prepared:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--validated:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/.
--prepared:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--validated:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/Squirrel.framework/Versions/Current/.
--prepared:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
--validated:/Users/myuser/Downloads/osx/myapp.app/Contents/Frameworks/ReactiveCocoa.framework/Versions/Current/.
/Users/myuser/Downloads/osx/myapp.app: valid on disk
/Users/myuser/Downloads/osx/myapp.app: satisfies its Designated Requirement
```

I don't see anything wrong.

**Comment by aekeus** [comment]
We are experiencing the identical issue while updating an Electron app. codesign is showing everything as signed correctly. Any updates on this issue?

**Comment by joshaber** [comment]
I don't have any other ideas off the top of my head. If someone could provide a small, self-contained example it'd be easier to debug.

**Comment by tom2zip** [comment]
I think I found the error and it's something trivial too, I feel so dumb :(
Instead of having a .app file in the zip file, I had something else

**Comment by bitomule** [comment]
Yeah, same issue here. I was uploading the dmg inside zip.

**Comment by joshaber** [comment]
:+1: Sounds like this is safe to close then.

**Comment by keithduncan** [comment]
Could the error messaging here be improved to help find this issue faster in the future?

**Comment by gopikrishnaA** [comment]
did you guys figured out that .app file should present inside the zip file instead of dmg file

**Comment by tarjei** [comment]
Any tips on how to debug this?

**Comment by iggyZiggy** [comment]
had same issue, build that was on git release was not signed, uploaded a new signed version on git, decreased my package version and it worked on next run
