### ISSUE TITLE
Error changing certificate: Code signature at URL did not pass validation

### ISSUE THREAD

**Issue by sergiovilar** [Squirrel/Squirrel.Mac#160]
Hello!

Currently my application is distributed using a Apple Developer certificate in the codesign process. But the Developer Certificate by itself is not enought to the "Mac Apple Store and identified developers" security level:

![Screeshot](http://d.pr/i/X8bj.jpg)

So, I generated an Apple Store certificate and used in my codesign process, but during the update I received this error:

```
Code signature at URL file:///Users/sergiovilar/Library/Application%20Support/com.electron.hackhands.ShipIt/update.2odv0kE/HackHands.app/ did not pass validation: code failed to satisfy specified code requirement(s)
```

Could someone help me?

**Comment by keithduncan** [comment]
For an update to be considered valid it must meet the *designated requirement* of the current version.

This is done to verify the authenticity of a given update, and to prevent a malicious update from being installed over the top of a genuine version.

To find what the designated requirement of your published application is run the following:

```
codesign -d -v -r - /Path/To/MyApplication.app/
```

it will print something of the form:

```
designated => (anchor apple generic and certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = MYTEAMID) and identifier "com.mycompany.myapp"
```

If you’ve changed the certificate your application is signed by it is likely now *not* meeting the designated requirement of the old versions.

There is a way to fix this! You can issue an update to your application signed by your old code signing identity that includes a new designated requirement, one that covers both the old and the new code signing identity. This version will then be able to update to an updated signed with the new identity.

NB to ensure you don’t orphan some of your users, you will need to use server side logic to force all users to download this ‘pivot’ update. This is exactly the kind of thing Squirrel.Mac was designed for. Users on <pivot version should have the pivot version returned to them, users on >=pivot should have the latest release returned to them.

**Comment by sergiovilar** [comment]
@keithduncan that's great! Thanks for the explanation but how can I include another designated requirement?

**Comment by keithduncan** [comment]
The [Code Signing Guide](https://developer.apple.com/library/mac/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW4) covers providing a custom requirement, there’s probably a build setting in Xcode to provide a requirements file but I don’t know what it is off the top of my head. Good luck :bow:

**Comment by jamesopti** [comment]
@sergiovilar - Were you able to figure this out?

I'm running into the same issue.

**Comment by Ajeey** [comment]
@sergiovilar Did you get any info on this? Having the same issue.

**Comment by sergiovilar** [comment]
I'm sorry guys, I wasn't able to fix the issue because I no longer work on the project.

**Comment by suryart** [comment]
@keithduncan 

Can you help with config details for this?

> NB to ensure you don’t orphan some of your users, you will need to use server side logic to force all users to download this ‘pivot’ update. This is exactly the kind of thing Squirrel.Mac was designed for. Users on <pivot version should have the pivot version returned to them, users on >=pivot should have the latest release returned to them.

I have looked over docs and google, but could not find anything relevant.

**Comment by spamshaker** [comment]
ehh I land here How to debug this frustrating thing?
