### ISSUE TITLE
Allow hosting updates on static web servers with no control over response status code

### ISSUE THREAD

**Issue by salomvary** [Squirrel/Squirrel.Mac#167]
In order to enable simple applications to host their updates on static web servers where there is no control over response status codes (ie. no way to meet this requirement: "If no update is required your server must respond with a status code of **204 No Content**.") allow 404 or 200 with zero length response to update requests when no update is available. (Maybe as a configurable option?)

Use case: host updates on GitHub/GitHub Pages.

**Comment by joshaber** [comment]
Agreed that would be nice. We're already tracking this in #64.
