### ISSUE TITLE
zip file does not download from Windows servers

### ISSUE THREAD

**Issue by brandon-7** [Squirrel/Squirrel.Mac#168]
The zip file that is specified as the url in my json update file does not download when on Azure or an IIS web server.  The file is being served (I can download the file by typing the url in a browser) but the update process fails to download it.  

I moved my zip file to Amazon's S3 service and it downloads correctly (http://mybucket.s3-website-us-east-1.amazonaws.com/myapp.zip)

**Comment by keithduncan** [comment]
> The zip file that is specified as the url in my json update file does not download when on Azure or an IIS web server. [...] I moved my zip file to Amazon's S3 service and it downloads correctly

I’d start by looking at a network packet trace using something like https://www.charlesproxy.com or Wireshark to see where the HTTP responses differ.

My guess is that this is something to do with Accept types and the response Content-Type, but it’s hard to say without more data.

**Comment by brandon-7** [comment]
Okay, I'll close this until I setup another test server.
