### ISSUE TITLE
Gatekeeper Path Randomization makes life hard

### ISSUE THREAD

**Issue by joshaber** [Squirrel/Squirrel.Mac#182]
1. Use macOS Sierra.
2. Download an app to `~/Downloads`.
3. Launch app.
4. Update found.
5. Prompted to auth update helper (??)
6. Update can't be installed.

This is because of Gatekeeper's path randomization, new in Sierra. Once you do something that deactivates path randomization (e.g., move the app), updates are fine.

This sucks. It's not terribly clear how we can deal with it. Try to detect it and tell users? Maybe we can explicitly de-quarantine the running app from ShipIt?

**Comment by joshaber** [comment]
@keithduncan krona for your thoughts.

**Comment by joshaber** [comment]
Some other discussions about this:

https://github.com/potionfactory/LetsMove/issues/56
http://www.openradar.me/radar?id=5022734169931776

**Comment by joshaber** [comment]
I've confirmed that removing `com.apple.quarantine` from the app fixes this. So what if we did this:

1. Check for updates.
2. Notice the host app still has `com.apple.quarantine`.
3. Clear the bit.
4. Since the app was launched with `com.apple.quarantine`, we can't update it until it's relaunch, so don't check for updates.

It sucks that it means they won't get updates on the first run, but... that's not too bad compared to the current behavior.

**Comment by joshaber** [comment]
Assuming #432 is misguided... I'm struggling to come up with any other ideas. We could try to detect when path randomization is being applied and just not check for updates?

**Comment by zorgiepoo** [comment]
Just found this thread while googling for something else related. We documented the issue for Sparkle at: https://github.com/sparkle-project/Sparkle/issues/832 https://sparkle-project.org/documentation/

In short, we do nothing special, other than disabling updates if the app is running from a read-only mount, which needs to be handled anyway if the app is running inside a dmg.

Apple wants developers to ship code signed dmg's now to avoid translocation and not zips. Maybe not ideal, but we'd rather not oppose them by writing a hack to clear a quarantine bit. App developers could use something like LetsMove if they want, but we don't handle that kind of logic ourselves.

**Comment by joshaber** [comment]
Thanks @zorgiepoo!

>In short, we do nothing special, other than disabling updates if the app is running from a read-only mount, which needs to be handled anyway if the app is running inside a dmg.

I think you're right that this is the best path forward 👍

**Comment by joshaber** [comment]
#186 addressed this as best as I know how for now.

**Comment by repertor** [comment]
I am directed to this issue when I try to update Atom. I am **not** running Atom from a read-only location, nor is it in my Downloads folder. It is in a subfolder of my Dropbox, located in my user directory. And yet, I receive the error message that follows:

> Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.

**Comment by himynameisjonas** [comment]
@repertor I had the same issue and also not running from a read-only volume but i just did what the first post here said:
> Once you do something that deactivates path randomization (e.g., move the app), updates are fine.

I moved it out of my applications folder and back again and the updater worked fine. (I guess I moved the Atom.app into the applications folder with Alfred.app instead of just moving it in Finder)

**Comment by repertor** [comment]
Thanks, @himynameisjonas. I had unzipped Atom directly into the directory from the download, so moving it in and out solved the problem.

**Comment by shaunc** [comment]
@himynameisjonas @repertor -- I tried 
```
$ mv /Applications/Atom.app ~
$ mv ~/Atop.app /Applications
```
but it had no effect. Is there some trick about how you move?

**Comment by himynameisjonas** [comment]
I just dragged it to the desktop and back in the Finder.

--
Jonas Brusman

**Comment by joshaber** [comment]
@shaunc You may need to move it using the Finder for it to work.

**Comment by albertbuchard** [comment]
sudo chown -R $(whoami):admin /Applications/Atom.app/

**Comment by avner-hoffmann** [comment]
Hi, what was the decision about this issue?
To do nothing?

**Comment by caioalmeida97** [comment]
Hello

I tried dragging the Atom.app from the Applications folder into the Desktop (just like @himynameisjonas said), but it just creates a new Atom.app alias, and when i drag the Atom.app alias back to the Applications folder, nothing happens.

Any ideas of what to do?

**Comment by weshicks** [comment]
@caioalmeida97 CMD + drag to the desktop so that it doesn't create shortcut. I was having this problem with VS Code and this solved it for me. (Make sure the app isn't running just to be safe.)

**Comment by merriam** [comment]
Please do note:
1.  The issue is "closed".  It was not "resolved".  The shortest answer is "sometimes goes away; live with it."
2.  New users run into this on their first exposure to Atom.  That is, the first impression is "OK, Atom only works sometimes".

**Comment by mrmass** [comment]
FYI - I'm new to mac platform, but the update only started working when I restarted my mac after the move from Downloads to Applications via Finder.

Not sure whether it's normal or not but it might save someone a bit of trouble...

**Comment by hassenius** [comment]
For anyone arriving here, here's what solved the problem for me:

1. Shutdown Atom
2. Run (in a terminal)
```
mv ~/Downloads/Atom.app ~/Applications/
xattr -dr com.apple.quarantine ~/Applications/Atom.app
```
3. Start Atom again
 It was now able to run updates no problem

**Comment by aberezin** [comment]
That wfm. Specifically
1. shutdown Atom
2. cd /path/to/my/apps/
3. xattr -dr com.apple.quarantine ./Atom.app

**Comment by lukasz-formela** [comment]
Hello! 
As @mrmass stated: 
Not only you have to move the app but you also need to restart the platform. 
Kudos!

**Comment by m-lamarre** [comment]
> I moved it out of my applications folder and back again and the updater worked fine.

Thanks @himynameisjonas 
This worked for me. My Atom was in the Applications folder. So I moved it to the Desktop and back, and now Updates are downloading 😅 🤷‍♀ 🤦‍♀

**Comment by willthemoor** [comment]
Running OXS 10.14.5. Had the app installed in `/Applications`. 

Moving it to the desktop and back via Finder did not work. Permissions looked right via cli.

`xattr -dr com.apple.quarantine /Applications/Atom.app/`
and
`xattr -dr com.apple.quarantine /Applications/Atom\ Beta.app/`
worked for me.

**Comment by zorgiepoo** [comment]
That's working as expected for app translocation (i.e, you need to move the app *using* Finder to have auto-updates available). Atom needs to update Squirrel so it doesn't try to auto-update in that scenario and/or ship their app in a signed dmg. That's an issue for Atom, not here.

**Comment by zorgiepoo** [comment]
Actually I take that back.. Looking at the code it looks like squirrel tries to notify the user if an update is available. It shouldn't. It should silently fail unless the user manually requests for an update like Sparkle. Responsibility is left to the apps or other frameworks (eg LetsMove) if they want the app to not be on a read-only volume. To each their own.

**Comment by dan003400** [comment]
This is happening when the Atom.app resides in ~/Applications

**Comment by jhriv** [comment]
Verified: using Iterm2 to mv ~/Downloads/Atom.app to /Applications keeps the read-only error. Using Finder to drag and drop it to /Applications allows the updater to function.

macOS Mojave Version 10.14.6

**Comment by MichaelRDionne** [comment]
> I just dragged it to the desktop and back in the Finder.
> […](#)
> -- Jonas Brusman
> On 28 aug. 2017 20:33 +0200, Shaun Cutts ***@***.***>, wrote: @himynameisjonas @repertor -- I tried $ mv /Applications/Atom.app ~ $ mv ~/Atop.app /Applications but it had no effect. Is there some trick about how you move? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.


Yep, same here. 
1. I quit VSC 
2. moved the APP from downloads to Applications
3. opened VSC from inside the Applications folder.

Worked fine after that. Hope that helps.

**Comment by natthachai043** [comment]
> 1. Use macOS Sierra.
> 2. Download an app to `~/Downloads`.
> 3. Launch app.
> 4. Update found.
> 5. Prompted to auth update helper (??)
> 6. Update can't be installed.
> 
> This is because of Gatekeeper's path randomization, new in Sierra. Once you do something that deactivates path randomization (e.g., move the app), updates are fine.
> 
> This sucks. It's not terribly clear how we can deal with it. Try to detect it and tell users? Maybe we can explicitly de-quarantine the running app from ShipIt?

**Comment by francip** [comment]
I started getting this in pgAdmin4. The app has been running for the past five months from the Applications folder. The only thing that changed was I updated my Mac Mini to Tahoe 26.0.1. When I installed the app I moved it to Applications using Finder.

Version
9.8
Application Mode
Desktop
Commit
500a5c7101726e919ebd56547eaf335c96cc4625 2025-09-02
Python Version
3.13.7
Current User
pgadmin4@pgadmin.org
Electron Version
37.4.0
Browser
Chrome 138.0.7204.243
Operating System
macOS-26.0.1-arm64-arm-64bit-Mach-O
pgAdmin Database File
/Users/francip/.pgadmin/pgadmin4.db
Log File
/Users/francip/.pgadmin/pgadmin4.log

**Comment by bladerunner2020** [comment]
> I started getting this in pgAdmin4. The app has been running for the past five months from the Applications folder. The only thing that changed was I updated my Mac Mini to Tahoe 26.0.1. When I installed the app I moved it to Applications using Finder.
> 
> Version 9.8 Application Mode Desktop Commit 500a5c7101726e919ebd56547eaf335c96cc4625 2025-09-02 Python Version 3.13.7 Current User [pgadmin4@pgadmin.org](mailto:pgadmin4@pgadmin.org) Electron Version 37.4.0 Browser Chrome 138.0.7204.243 Operating System macOS-26.0.1-arm64-arm-64bit-Mach-O pgAdmin Database File /Users/francip/.pgadmin/pgadmin4.db Log File /Users/francip/.pgadmin/pgadmin4.log

Have the same issue

**Comment by grafpaper1987** [comment]
> I started getting this in pgAdmin4. The app has been running for the past five months from the Applications folder. The only thing that changed was I updated my Mac Mini to Tahoe 26.0.1. When I installed the app I moved it to Applications using Finder.

Same issue

**Comment by said7388** [comment]
Same issue

**Comment by JustinMacri007** [comment]
I have the newest Mac OS and Vscode is not updating.

**Comment by rtilakv-eng** [comment]
I have the newest Mac OS and Vscode is not updating.

<img width="1800" height="1169" alt="Image" src="https://github.com/user-attachments/assets/be817f28-d031-409b-a0a2-d56690bbecd0" />

**Comment by lasithchandrasekara** [comment]
> I have the newest Mac OS and Vscode is not updating.
> 
> <img alt="Image" width="1800" height="1169" src="https://private-user-images.githubusercontent.com/235247518/534251125-be817f28-d031-409b-a0a2-d56690bbecd0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzE3NzI4NzAsIm5iZiI6MTc3MTc3MjU3MCwicGF0aCI6Ii8yMzUyNDc1MTgvNTM0MjUxMTI1LWJlODE3ZjI4LWQwMzEtNDA5Yi1hMGEyLWQ1NjY5MGJiZWNkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDIyMlQxNTAyNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGUzMWJkMWU4NzZhNjZiOTIyOWVjYjdkODk1YzYwNjYzYjVmMmU3N2I0OTBjMmQxOWU1NThlNGMwNmUyNWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bAVikMk6CVUp5iZfwNKO4pZ-QLmdLi-dOCLUlMIYEZs">

same issue, anyone got a solution ?

**Comment by laurilarjo** [comment]
I encountered this too with pgAdmin.
The issue is fixed in pgAdmin's #9402 but it requires you to manually reinstall the pgAdmin to 9.12.
Then future updates should work. See last msg in https://github.com/pgadmin-org/pgadmin4/issues/9402

**Comment by candih444** [comment]
I encountered this too. Anyone find how to fix it? Can I uninstall and reinstall?

**Comment by gcost81** [comment]
Even when moving the application to "Applications" it still gives me the following message: 

_Failed to check for updates: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory._

so strange
