### ISSUE TITLE
checking-for-update times out when receiving 204 response (with Content-Length header)

### ISSUE THREAD

**Issue by rsaccon** [Squirrel/Squirrel.Mac#184]
with electron 1.4.2 and custom update server on Amazon Lambda / ApiGateway, I can successfully detect, download and install an update, but when no update is available, and the server returns a 204 status, then the request times out. Below the verbose output, if I do it with curl:

```
$ *   Trying 54.230.149.238...
* Connected to 7yqrw9kjal.execute-api.us-east-1.amazonaws.com (54.230.149.238) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.execute-api.us-east-1.amazonaws.com
* Server certificate: Symantec Class 3 Secure Server CA - G4
* Server certificate: VeriSign Class 3 Public Primary Certification Authority - G5
> GET /prod/latestRelease?version=0.0.2 HTTP/1.1
> Host: 7yqrw9kjal.execute-api.us-east-1.amazonaws.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Content-Type: application/json
< Content-Length: 70
< Connection: keep-alive
< Date: Thu, 06 Oct 2016 07:06:12 GMT
< x-amzn-RequestId: 5d6063a8-8b93-11e6-b3c9-67474ab803ac
< X-Cache: Miss from cloudfront
< Via: 1.1 4ca8c03598e35c3d746933569ed74033.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: zwutVZ8xzzcJbNDgyoi1d1VAnGhvk5VS6LyLPQ91V8JKeumLvxAOOg==
< 
* Connection #0 to host 7yqrw9kjal.execute-api.us-east-1.amazonaws.com left intact

[1]+  Done
```

The problem might be that I get back a Content-Length header, which is not what one would expect, when receiving a 204 code. Unfortunately I am not aware of any way to [get rid of that header](https://forums.aws.amazon.com/thread.jspa?messageID=745238&#745238).

I might just have overseen something causing the issue, if not, Amazon Lambda / ApiGateway is a great, simple, cheap and maintenance-less way to run an update server, it would be great if squirrel just would  work on it, even if 204 response is not fully according to specification (or provide as alternative way, just a 200 OK response with no or different fields than when there is an update available)

**Comment by keithduncan** [comment]
As there's no update is it causing issues for the request to time out?

We use the built in NSURLConnection class to issue HTTP requests, if the AWS API Gateway violates the HTTP specification there's not much we can do. Have you tried including a body in the 204 response? That might be another spec violation but it might be one that works :laughing:

**Comment by rsaccon** [comment]
It is not causing any immediate issues, however I do not know whether it might have any negative impact on `startAutomaticChecksWithInterval`, but I actually do not know whether that is even used in electron and how it can be configured.

Ok, I will try to include a body

**Comment by joshaber** [comment]
Closing until we know if Squirrel.Mac was at fault.
