### ISSUE TITLE
com.mydomain.ShipIt respawn every 2 second, spamming user's system.log

### ISSUE THREAD

**Issue by psequel** [Squirrel/Squirrel.Mac#185]
This is spamming user's system.log every 2 seconds.

```
com.apple.xpc.launchd[1] (com.mydomain.ShipIt): Service only ran for 0 seconds. Pushing respawn out by 2 seconds.
com.apple.xpc.launchd[1] (com.mydomain.ShipIt): Service could not initialize: ...
```

### Steps to reproduce

1. Download an app with Squirrel as updater to ~/Downloads folder
2. Open the app from within Downloads folder
3. When it's time to update, the app will prompt the user to enter her password to "install a helper tool"
4. The user clicks "Cancel" because the prompt looks suspicious
5. Now the user's system.log gets spammed every 2 seconds
6. She moves the app to /Applications, but spams won't stop
7. She Deletes the app,  spams stop
8. She still likes your app so she downloads it again and moves it to /Applications immediately
9. Spams continue, before she even tries to run the app for the first time
10. She deletes the app, for real, never look back. The end of story.

### macOS version

Sierra 10.12

### Squirrel version

0.2.1

**Comment by joshaber** [comment]
I'm betting this is #182.
