### ISSUE TITLE
"URL not Supported"?

### ISSUE THREAD

**Issue by SantoDE** [Squirrel/Squirrel.Mac#191]
Hey there,

I'm having a weird issue with the auto updater for my electron based app. Everytime it tries to check for an update, I end up with an error "url not supported". My Feed Url itself seems to be fine. https://releases.cnx.de/update/darwin/0.3.3

My App is also signed with Developer ID certificates, so I'm a litte lost.

Did someone encounter this issue before?

**Comment by joshaber** [comment]
I don't see that error message in Squirrel.Mac.
