### ISSUE TITLE
What should I use for a MAC .NET app?

### ISSUE THREAD

**Issue by TonyValenti** [Squirrel/Squirrel.Mac#193]
Hi Squirrel,
I'm building a .NET app that will run on Macs.  What package should I use for updating?  Is Squirrel.Windows for just windows or .NET in general?  Should I use Squirrel.Mac?

**Comment by joshaber** [comment]
This isn't really a question about Squirrel.Mac. I'm not sure what the appropriate update solution is for .NET apps.
