### ISSUE TITLE
Bootstrap an .app with Squirrel.Mac just with an URL on a Squirrel server

### ISSUE THREAD

**Issue by Skywalker13** [Squirrel/Squirrel.Mac#198]
Hello,

I would like to use Squirrel.Mac in order to install a `.app` which is not already installed. I can do that with **Squirrel.Windows** because `Update.exe` is provided as a standalone application and doing `Update.exe --update=http://my.repository` will download the last version and install this version where `Update.exe` is located. It's very useful for bootstrapping an app on the client. Just put `Update.exe` in the right `%localappdata%` directory, call it and the magic happens.

But I cannot see any possibilities for doing that with **Squirrel.Mac**. Have you a tool where it's possible to pass a squirrel URL in order to bootstrap a first installation please?

I looked for ShipIt but it seems that it's just for deploying from the cache to the final destination.

Thanks,
Regards

**Comment by joshaber** [comment]
No, Squirrel.Mac doesn't provide anything like that.

Mac apps generally shouldn't require installation. Users should be able to drop them wherever they want and they should work.

**Comment by Skywalker13** [comment]
Yep that's the problem.. the user can not do that because our electron app is used like a service. This "service" is installed by the main application according to some conditions. Then it downloads the service if the conditions are met. It works perfectly with Squirrel.Windows for this purpose.

So, I will write my own "UpdateMac" tool in order to mimic the needed Update.exe stuff.
