### ISSUE TITLE
Squirrel tries to escalate privileges even when user owns the parent directory

### ISSUE THREAD

**Issue by joaomoreno** [Squirrel/Squirrel.Mac#199]
- Coming from Microsoft/vscode#7426
- Same as atom/atom#2860, electron/electron#6345

Very similar to #131, all the symptoms are the same... but there's a different twist.

With a VSCode build, in a fresh new macOS 10.12.3:

- If the application bundle is in `~/Desktop` or `~/Downloads`, I get exactly the same behaviour as #131: there's a Helper dialog coming up asking for credentials, and the update fails.
- If the application bundle is in `/Applications`, I get **no helper dialog**, the update just succeeds.

Why is there an escalation dialog coming up, even when the user owns the folder?

**Comment by joaomoreno** [comment]
I now see what the difference is: when launching from `~/Desktop` or `~/Downloads`, `htop` says the process running is:

```
/private/var/folders/6t/nm18ywnx13lghb8ccx3js2mc0000gn/T/AppTranslocation/2B87D66E-E1C2-4F24-A64A-4A71F73C4940/d/Visual Studio Code - Insiders.app
```

Here are the permissions:

```
➜  ~ ls -la /private/var/folders/6t/nm18ywnx13lghb8ccx3js2mc0000gn/T/AppTranslocation/2B87D66E-E1C2-4F24-A64A-4A71F73C4940/d                               
total 0
dr-xr-xr-x  3 joao  staff    0 Feb  6 16:51 .
dr-xr-xr-x  3 joao  staff    0 Feb  6 16:51 ..
drwxr-xr-x@ 3 joao  staff  102 Nov  9 16:15 Visual Studio Code - Insiders.app
```

The parent folder is not writable by me! This would make [this code](https://github.com/Squirrel/Squirrel.Mac/blob/master/Squirrel/SQRLUpdater.m#L255) try to update with priviledges.

**Comment by joshaber** [comment]
Yup, this is https://github.com/Squirrel/Squirrel.Mac/issues/182. I would have thought https://github.com/Squirrel/Squirrel.Mac/pull/186 would surface a more user-friendly error.

**Comment by joaomoreno** [comment]
Absolutely, closing as dupe of #182, thanks @joshaber
