### ISSUE TITLE
Squirrel.framework 0.3.1 contains ShipIt binary 0.3.0

### ISSUE THREAD

**Issue by jiri-nohavec** [Squirrel/Squirrel.Mac#212]
**How to reproduce:**
* download and extract latest Squirrel.framework 0.3.1 from https://github.com/Squirrel/Squirrel.Mac/releases/tag/0.3.1
* run in terminal:
  ./Squirrel.framework/Resources/ShipIt

**Expected output:**
(according to https://github.com/Squirrel/Squirrel.Mac/blob/5396dcd1f94bfa66eebd091d331427654918ed4d/Squirrel/ShipIt-main.m#L149 or https://github.com/Squirrel/Squirrel.Mac/archive/0.3.1.zip)
"Missing launchd **>>>job label or state path<<<** for ShipIt"

**Actual output:**
2017-08-18 09:58:56.277 ShipIt[86751:6657135] Missing launchd **>>>job label<<<** for ShipIt

---

**Which means Squirrel.framework 0.3.1 contains ShipIt binary 0.3.0, or even older** . Or there is some other mismatch in build/pack/release process. Same for latest Electron 1.7.6 and its copy of Squirrel.framework.

**Not sure, whether there is some compatibility issue caused by older ShipIt or not.** On first glance it _should_ still work, just #207 fix is not applied.

I found this while trying 0.3.1 and its #207 fix in our Electron app.

**Comment by jiri-nohavec** [comment]
@joshaber

**Comment by joshaber** [comment]
Wow, I'm not sure how that happened. Great catch @jiri-nohavec!

**Comment by joshaber** [comment]
[0.3.2](https://github.com/Squirrel/Squirrel.Mac/releases/tag/0.3.2) created and an PR to update Electron [opened](https://github.com/electron/electron/pull/10298).

Thanks again @jiri-nohavec!
