### ISSUE TITLE
ShipIt not finding ReactiveCocoa

### ISSUE THREAD

**Issue by mRs-** [Squirrel/Squirrel.Mac#237]
```
dyld: Library not loaded: @rpath/ReactiveCocoa.framework/ReactiveCocoa
  Referenced from: …/myAppPath.app/Contents/Frameworks/Squirrel.framework/Resources/ShipIt
  Reason: image not found
```

It seems that ShipIt is not finding the Path to ReactiveCocoa. Maybe ShipIt is in the Resources Folder?

Currently I'm implementing Squirrel with Carthage… Seems not to work right now out of the box…

**Comment by MarshallOfSound** [comment]
@mRs- I believe the issue you are seeing is fixed by https://github.com/Squirrel/Squirrel.Mac/pull/236 and caused by b426994d83539dd395bb838093b3d31c6cb72cea

I just reverted that commit now (thought I had already, sorry about that)

Refs: b5ce589c4ca5d61388f555a8fd4a7705a114e427

**Comment by mRs-** [comment]
Yep it's now working.

A Carthage release for the recent version would also be a fine thing :)

Cheers and thanks for your help!
