### ISSUE TITLE
Squirrel should support static update resources

### ISSUE THREAD

**Issue by keithduncan** [Squirrel/Squirrel.Mac#64]
If we expect the server to branch on which response (update/no update) to send based on the version provided by the requester, whether that version is in a header or a query parameter, we can’t support static files.

So, is static file support important? If so we need to move the version equality check into the client so that it can retrieve the plain file and not update if the versions are the same. If it isn’t we need to remove that note from the docs and ensure that if the releases API supports Squirrel, it includes support for the same version comparison for Squirrel that Central does and Speakeasy will.

/cc @github/mac

**Comment by gerges** [comment]
@dannygreg I know it's been some time, but what sort of long-term plans were you thinking? I'm thinking about tackling this now, since it seems like a tempting way to have a easy high-scale update distribution mechanism (CloudFront + S3)

**Comment by bhajneet** [comment]
Can't we just format the jquery to say "No update" instead of relying on status codes?

Update:

```
{
    "update": "true",
    "url": "update.com/server/stuff"
}
```

No update:

```
{
    "update": "false"
}
```

**Comment by romaincointepas** [comment]
It's also worth noting that Cloudflare does not allow caching of 204 responses (even with all the rules set to caching), meaning this issue also concerns standard non-static distribution model with Cloudflare on top.
