### ISSUE TITLE
Updates aren’t always cleaned up

### ISSUE THREAD

**Issue by robrix** [Squirrel/Squirrel.Mac#95]
In ~/Library/Application Support/com.github.GitHub.ShipIt/, I have a number of update.<hash> folders containing .zips of builds of GitHub for Mac, and a couple which are empty. Additionally, at least one user has reported something similar where the actual .app bundles are still present (and indexed by Alfred).
1. Is it safe for me (and the user) to delete these?
2. Is Squirrel not tidying sufficiently?

**Comment by PetrKarbula** [comment]
I had in that folder 3.46gb worth of updates :sweat_smile:
